<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */

use Magento\Framework\View\Element\Template; ?>
<?php
/** @var Template $block */
$xData = [
    'name' => '',
    'email' => ''
]
?>
<script>
    window.zermatt_form = function () {
        return {
            success: false,
            submitted: false,
            form: null,
            init() {
                if (Zermatt.Variables.formKey) {
                    this.buildForm()
                } else {
                    Zermatt.Event.listen('zermatt:form:key:init', this.buildForm.bind(this))
                }
            },
            buildForm() {
                const form = this.$el.querySelector('form')
                let formData = JSON.parse(form.getAttribute('x-data'))
                formData.form_key = Zermatt.Variables.formKey
                this.form = this.$form('post', form.getAttribute('action'), formData)
            },
            onSuccess(response) {
                window.location.href = response.data.redirect
            },
            submit() {
                this.submitted = true
                let form = this.$el.querySelector('form')
                this.form.submit()
                    .then(response => {
                        this.form.reset()
                        form.reset()
                        this.success = true
                        this.submitted = false
                        this.onSuccess(response)
                        setTimeout(() => {
                            this.success = false
                        }, 4500)
                    })
                    .then(() => form.scrollIntoView())
                    .catch(error => {
                        console.log('Form has errors and was not submitted.')
                    })
            }
        }
    }
</script>
<div x-data="zermatt_form()" x-cloak>
    <form x-data='<?= json_encode($xData) ?>' action="<?= $block->getUrl('zermatt_examples/form') ?>">
        <template x-if="form">
            <div>
                <?php zermatt_component('Maddlen_ZermattExamples::components/form/text.phtml', ['label' => __('Name'), 'id' => 'name', 'name' => 'name']) ?>
                <?php zermatt_component('Maddlen_ZermattExamples::components/form/error.phtml', ['target' => 'name']) ?>

                <?php zermatt_component('Maddlen_ZermattExamples::components/form/text.phtml', ['label' => __('Email'), 'id' => 'email', 'name' => 'email']) ?>
                <?php zermatt_component('Maddlen_ZermattExamples::components/form/error.phtml', ['target' => 'email']) ?>

                <?php zermatt_component('Maddlen_ZermattExamples::components/form/button.phtml', ['label' => __('Submit')]) ?>
            </div>
        </template>
    </form>
</div>
<div x-data="zermatt_form()" x-cloak>
    <form x-data='<?= json_encode($xData) ?>' action="<?= $block->getUrl('zermatt_examples/form') ?>">
        <template x-if="form">
            <div>
                <?php zermatt_component('Maddlen_ZermattExamples::components/form/text.phtml', ['label' => __('Name'), 'id' => 'name', 'name' => 'name']) ?>
                <?php zermatt_component('Maddlen_ZermattExamples::components/form/error.phtml', ['target' => 'name']) ?>

                <?php zermatt_component('Maddlen_ZermattExamples::components/form/text.phtml', ['label' => __('Email'), 'id' => 'email', 'name' => 'email']) ?>
                <?php zermatt_component('Maddlen_ZermattExamples::components/form/error.phtml', ['target' => 'email']) ?>

                <?php zermatt_component('Maddlen_ZermattExamples::components/form/button.phtml', ['label' => __('Submit')]) ?>
            </div>
        </template>
    </form>
</div>
