<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */

use Magento\Framework\View\Element\Template; ?>
<?php
/** @var Template $block */
$xData = [
    'name' => '',
    'email' => ''
]
?>
<form
    x-ref="form"
    action="<?= $block->getUrl('zermatt_examples/form') ?>"
    x-data='<?= json_encode($xData) ?>'
>
    <div x-data="zermatt_form" x-cloak>
        <template x-if="form">
            <div>
                <?php zermatt_component('Maddlen_ZermattExamples::components/form/text.phtml', ['label' => __('Name'), 'id' => 'name', 'name' => 'name']) ?>
                <?php zermatt_component('Maddlen_ZermattExamples::components/form/error.phtml', ['target' => 'name']) ?>

                <?php zermatt_component('Maddlen_ZermattExamples::components/form/text.phtml', ['label' => __('Email'), 'id' => 'email', 'name' => 'email']) ?>
                <?php zermatt_component('Maddlen_ZermattExamples::components/form/error.phtml', ['target' => 'email']) ?>

                <?php zermatt_component('Maddlen_ZermattExamples::components/form/button.phtml', ['label' => __('Submit')]) ?>
            </div>
        </template>
    </div>
</form>
