<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */

use Maddlen\Zermatt\App\Variable;
use Magento\Framework\View\Element\Template;

?>
<?php
/** @var Template $block */
/** @var \Maddlen\Zermatt\App\App $app */
$app = $block->getData('app');
?>

<?php
/**
 * Inject the main app JS file.
 * This file must be created by running `npm install && npm run build`
 * in the theme's web/zermatt directory.
 */
?>
<script type="module" src="<?= $block->getViewFileUrl($app->entryFilepath()) ?>"></script>

<?php
/**
 * Declare the main Zermatt object and populate it with the list of variables
 * that backend wants to expose to frontend.
 *
 * The JS app will enrich the Zermatt object on page load
 * with additional features, utilities, etc.
 */
?>
<script>
    window.Zermatt = {
        Variables: JSON.parse('<?= json_encode(Variable::all()) ?>')
    }
</script>
