<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */

use Maddlen\Zermatt\App\Variable;
use Magento\Framework\View\Element\Template;

?>
<?php
/** @var Template $block */
/** @var \Maddlen\Zermatt\App\App $app */
$app = $block->getData('app');
?>
<script type="module" src="<?= $block->getViewFileUrl($app->entryFilepath()) ?>"></script>
<script>
    window.Zermatt = {
        Variables: JSON.parse('<?= json_encode(Variable::all()) ?>')
    }
</script>
